<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>warehousesLink</name>
   <tag></tag>
   <elementGuidId>7e3464e1-7157-46cd-b9e4-a973099e1b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fw-bold.text-truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Warehouses')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Warehouses&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>978bb414-2d67-4788-9a69-281bd5a7ea60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold text-truncate</value>
      <webElementGuid>9c48515f-9680-446d-9155-8379d8ed373f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/odoo/action-242</value>
      <webElementGuid>87641470-efa6-4df9-96d1-4fd250bd3b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Back to &quot;Warehouses&quot;</value>
      <webElementGuid>870bdb79-81cc-4abb-bf58-8089f4b66092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Warehouses</value>
      <webElementGuid>3dd3a9f6-3e9b-4d17-b1c5-9f890ee7feeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_form_view o_view_controller o_action&quot;]/div[@class=&quot;o_form_view_container&quot;]/div[@class=&quot;o_control_panel d-flex flex-column gap-3 gap-lg-1 px-3 pt-2 pb-3&quot;]/div[@class=&quot;o_control_panel_main d-flex flex-wrap flex-lg-nowrap justify-content-between align-items-lg-start gap-3 flex-grow-1&quot;]/div[@class=&quot;o_control_panel_breadcrumbs d-flex align-items-center gap-1 order-0 h-lg-100&quot;]/div[@class=&quot;o_breadcrumb d-flex flex-row flex-md-column align-self-stretch justify-content-between min-w-0&quot;]/ol[@class=&quot;breadcrumb flex-nowrap text-nowrap small lh-sm&quot;]/li[@class=&quot;breadcrumb-item d-inline-flex min-w-0 o_back_button&quot;]/a[@class=&quot;fw-bold text-truncate&quot;]</value>
      <webElementGuid>f184ca32-b8c6-48c3-a8f0-22df50e6eb1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Warehouses')]</value>
      <webElementGuid>82874e65-7e35-4b05-912a-0e7a4249f81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::a[1]</value>
      <webElementGuid>e1530d32-051e-48e9-a35c-38e3f7a7002a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[1]/following::a[1]</value>
      <webElementGuid>a7cffb93-0303-4ca2-861e-9cfa39e9cefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Routes'])[1]/preceding::a[1]</value>
      <webElementGuid>593d5d51-7764-4783-a54d-dac1b9322d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::a[1]</value>
      <webElementGuid>6808a709-265a-41fc-bdc7-053a724560f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Warehouses']/parent::*</value>
      <webElementGuid>89cc5e52-9bff-4605-8cb5-89b717057bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/odoo/action-242')]</value>
      <webElementGuid>16be27ac-a3b0-4186-aead-8b4bd129aecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>230b6a1e-2fc7-4dac-ace4-f6f4ffe98bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/odoo/action-242' and (text() = 'Warehouses' or . = 'Warehouses')]</value>
      <webElementGuid>254c30cf-9bb9-42c1-a4c4-662f96f03d35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
