<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Replenishment_link</name>
   <tag></tag>
   <elementGuidId>b6051e45-89fe-4bd5-a640-4bf8b04fa2f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.o-dropdown-item.dropdown-item.o-navigable.o_dropdown_menu_group_entry.focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Replenishment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Replenishment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>102d1b84-0d0f-41e0-b436-bd0b66dadc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-dropdown-item dropdown-item o-navigable o_dropdown_menu_group_entry focus</value>
      <webElementGuid>d2eaced4-c283-4765-b553-7a483906f3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>39fc3e5b-f0dc-4b8a-8444-af0954e88411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98b691b0-d2da-4768-a95b-0993f78a41a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/odoo/action-277</value>
      <webElementGuid>49bd5054-c463-4780-95cc-0dad3f65ee3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-xmlid</name>
      <type>Main</type>
      <value>stock.menu_reordering_rules_replenish</value>
      <webElementGuid>04a5b5b9-77b8-4b4b-b7c2-69aac394bb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-section</name>
      <type>Main</type>
      <value>158</value>
      <webElementGuid>537cd8d8-170e-43ae-ae38-b8501bfaa30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Replenishment</value>
      <webElementGuid>2e646916-dc58-4652-aa9c-f20992dab20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o-main-components-container&quot;]/div[@class=&quot;o-overlay-container&quot;]/div[@class=&quot;o_popover popover mw-100 o-dropdown--menu dropdown-menu mx-0&quot;]/a[@class=&quot;o-dropdown-item dropdown-item o-navigable o_dropdown_menu_group_entry focus&quot;]</value>
      <webElementGuid>451d3d95-6a92-43c2-9daa-891fd050aa8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Replenishment')]</value>
      <webElementGuid>023f6ab9-1f74-41ad-ad39-e3e5d0e8d819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procurement'])[1]/following::a[1]</value>
      <webElementGuid>615456a7-4a2c-4fd0-8d0d-1d8749528e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scrap'])[1]/following::a[1]</value>
      <webElementGuid>78265272-dbd1-4509-b5ce-640736421d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Replenishment']/parent::*</value>
      <webElementGuid>de57efed-6e40-450c-b0ea-c5dc363469e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/odoo/action-277')]</value>
      <webElementGuid>78334d86-affd-4569-8722-e063ef7fea1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>a1174a73-f52f-4c19-855c-89e55e7cdfc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/odoo/action-277' and (text() = 'Replenishment' or . = 'Replenishment')]</value>
      <webElementGuid>b3e62658-e939-4176-a57b-3bd0a6c79872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
