<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Print Labels_fa fa-pencil fa-fw</name>
   <tag></tag>
   <elementGuidId>6495baab-86a0-45ae-8dcb-c533d482d5df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-pencil.fa-fw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Edit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>211c3e34-18da-4b21-9632-5915986d0054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil fa-fw</value>
      <webElementGuid>b702ce4c-df5d-4ef2-8c53-e8e1cc55cb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_form_view o_view_controller o_action&quot;]/div[@class=&quot;o_form_view_container&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_form_renderer o_form_editable d-flex flex-column o_form_dirty&quot;]/div[@class=&quot;o_form_sheet_bg&quot;]/div[@class=&quot;o_form_sheet position-relative&quot;]/div[@class=&quot;o_field_widget o_field_image oe_avatar&quot;]/div[@class=&quot;d-inline-block position-relative opacity-trigger-hover&quot;]/div[@class=&quot;position-absolute d-flex justify-content-between w-100 bottom-0 opacity-0 opacity-100-hover&quot;]/span[1]/button[@class=&quot;o_select_file_button btn btn-light border-0 rounded-circle m-1 p-1&quot;]/i[@class=&quot;fa fa-pencil fa-fw&quot;]</value>
      <webElementGuid>910fd155-ca25-40f9-a2f2-5fff76f970f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/i</value>
      <webElementGuid>7391a0ec-3195-42ba-9603-9d946f780601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
