<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_0.00</name>
   <tag></tag>
   <elementGuidId>bfefc624-4e9f-4d84-8eb1-a0635bcff5d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@name='qty_available']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td[name=&quot;qty_available&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7efd162c-6cbe-43e3-acdf-3d91aea05a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_data_cell cursor-pointer o_field_cell o_list_number o_readonly_modifier</value>
      <webElementGuid>5f157317-a3e4-43d1-a771-2aaab1be6730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-delay</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>bd5827d6-e276-4d7a-aeb5-d4330bc1ddac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>013ca334-d3b6-4716-b378-d81f88c8cb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qty_available</value>
      <webElementGuid>07bca3a2-25de-4d2e-83f3-94056181857c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>b9a3bad5-5bb5-46f7-a6ff-44a57a49d19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_list_view o_stock_report_list_view_view o_view_controller o_action&quot;]/div[@class=&quot;o_content o_component_with_search_panel&quot;]/div[@class=&quot;o_list_renderer o_renderer table-responsive&quot;]/table[@class=&quot;o_list_table table table-sm table-hover position-relative mb-0 o_list_table_ungrouped table-striped&quot;]/tbody[@class=&quot;ui-sortable&quot;]/tr[@class=&quot;o_data_row o_row_draggable&quot;]/td[@class=&quot;o_data_cell cursor-pointer o_field_cell o_list_number o_readonly_modifier&quot;]</value>
      <webElementGuid>39dc1d4f-c965-4ad6-ad71-1694d891d2ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@name='qty_available']</value>
      <webElementGuid>09e8f72c-0d72-49f9-8a90-62c8f96e4b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Computer Accessories] Wireless Headphones'])[1]/following::td[1]</value>
      <webElementGuid>bd1bb054-98b5-4834-b8e5-fb1cd8940586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outgoing'])[1]/following::td[3]</value>
      <webElementGuid>4a757c17-6e3a-471e-9e3a-5a6214b0a966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/preceding::td[5]</value>
      <webElementGuid>4953f3a4-ac13-44dd-a3e1-e510e0ee9303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replenishment'])[1]/preceding::td[5]</value>
      <webElementGuid>a9377b4a-c038-4c95-858c-9206fb15642b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0.00']/parent::*</value>
      <webElementGuid>2eb64190-a46f-4e12-91f0-01288d994837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>fedaff15-2a8e-4433-9eb0-0df2080774f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@name = 'qty_available' and (text() = '0.00' or . = '0.00')]</value>
      <webElementGuid>0eb2e5e0-1ac9-4cdf-b61f-55df4d673d8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
